### ISSUE TITLE
 if (pacman := archinstall.sys_command(f"pacman --noconfirm --config {pacman_build_config} -Syw {' 

### ISSUE THREAD

**Issue by layer7gmbh** [Torxed/archoffline#2]
Hi, 

reflector was installed by the way ;) Thx for the patch! Now this:

```
# python offline.py --mirrors=Sweden --packages="nano wget" --rebuild
Setting up a new build directory in /usr/src/archiso_offline
Copying the Arch ISO configuration releng to new build door /usr/src/archiso_offline.
Getting mirror list from the given region.
Patching pacman build configuration file.
Validating additional packages...
Syncronizing 82 packages (this might take a while)
Traceback (most recent call last):
  File "/usr/src/offline.py", line 187, in <module>
    if (pacman := archinstall.sys_command(f"pacman --noconfirm --config {pacman_build_config} -Syw {' '.join(packages)}")).exit_code != 0:
  File "/usr/lib/python3.9/site-packages/archinstall/lib/general.py", line 129, in __init__
    self.run()
  File "/usr/lib/python3.9/site-packages/archinstall/lib/general.py", line 259, in run
    raise SysCallError(message=f"{self.trace_log.decode('UTF-8')}\n'{self.raw_cmd}' did not exit gracefully (trace log above), exit code: {self.exit_code}", exit_code=self.exit_code)
archinstall.lib.exceptions.SysCallError: :: Synchronizing package databases...
 core                  131.1 KiB  1873 KiB/s 00:00 [######################] 100%
 extra                1599.6 KiB  17.4 MiB/s 00:00 [######################] 100%
 community               5.5 MiB   109 MiB/s 00:00 [######################] 100%
error: target not found: refind-efi

'pacman --noconfirm --config /usr/src/archiso_offline/pacman.build.conf -Syw nano wget arch-install-scripts b43-fwcutter broadcom-wl btrfs-progs clonezilla crda darkhttpd ddrescue dhclient dhcpcd dialog diffutils dmraid dnsmasq dnsutils dosfstools elinks ethtool exfat-utils f2fs-tools fsarchiver gnu-netcat gpm gptfdisk grml-zsh-config grub hdparm ipw2100-fw ipw2200-fw irssi iwd jfsutils lftp linux-atm linux-firmware lsscsi lvm2 man-db man-pages mc mdadm mtools nano ndisc6 netctl nfs-utils nilfs-utils nmap ntfs-3g ntp openconnect openssh openvpn partclone parted partimage ppp pptpclient refind-efi reiserfsprogs rp-pppoe rsync sdparm sg3_utils smartmontools sudo tcpdump testdisk usb_modeswitch usbutils vi vim-minimal vpnc wget wireless-regdb wireless_tools wpa_supplicant wvdial xfsprogs xl2tpd' did not exit gracefully (trace log above), exit code: 256
```

**Comment by Torxed** [comment]
This is not a archoffline issue. The package in your packages definition contains a invalid package: `refind-efi`.

The package you're looking for is probably [REfind](https://archlinux.org/packages/?name=refind)?

I can re-open if I missunderstood something, but this indicates that the issue is the given packages:
> error: target not found: refind-efi

Which is an error from pacman not archoffline.

**Comment by layer7gmbh** [comment]
Hi, 

to test your script, i am using a vanilla arch linux install that is some months old and running the command from your example:

```
python offline.py --mirrors=Sweden --packages="nano wget" --rebuild
```

So where ever this refind-efi is coming from, its not coming from a manual selection i did.

I installed archinstall as requirement, and didnt do any further installs or modifications of anything.

If my packages definition contains an invalid package, then this invalid package selection was provoked through something that was triggered automatically.

**Comment by Torxed** [comment]
> Hi,
> 
> to test your script, i am using a vanilla arch linux install that is some months old and running the command from your example:
> 
> ```
> python offline.py --mirrors=Sweden --packages="nano wget" --rebuild
> ```
> 
> So where ever this refind-efi is coming from, its not coming from a manual selection i did.
> 
> I installed archinstall as requirement, and didnt do any further installs or modifications of anything.
> 
> If my packages definition contains an invalid package, then this invalid package selection was provoked through something that was triggered automatically.

To reproduce this I would need `pacman -Q | grep archiso` from you.

**Comment by layer7gmbh** [comment]
Hi Anton,

here you go boss:

```
pacman -Q | grep archiso
archiso 43-2
```

**Comment by Torxed** [comment]
This is an issue with your archiso being outdated.
Your `/usr/share/archiso/configs/releng/packages.x86_64` package list is outdated, which means upstream mirrors won't have the packages as they have been removed or re-named on all active mirrors. This is a result of `archiso` being out of date, not an issue with archoffline as it simply uses `archiso` and it's tools to build the ISO in a offline manner.

So even following [archiso *(wiki)*](https://wiki.archlinux.org/index.php/Archiso#Build_the_ISO) will cause this issue for you.

Latest archiso is `52-1` and works:
![2021-04-27-094932_1163x380_scrot](https://user-images.githubusercontent.com/861439/116205965-92f0d600-a73e-11eb-8182-e5147a22550e.png)

Interestingly tho, perhaps I can add in support for archoffline to be pointed towards archive mirrors or custom mirrors - not just selecting active and updated mirrors.
